Repository mainmatter/sheepdog, pull requests merged in 2024-07, with the labels that each got.

#114 Add timeout utility function
  README.md
  src/lib/index.ts
  src/lib/tests/task.test.ts
  src/lib/tests/utils.test.ts
  src/lib/utils.ts
  src/routes/+page.svelte
  src/routes/Child.svelte
Labels: enhancement

#116 feat: add installation, usage and start docs
  .prettierignore
  .prettierrc
  README.md
  docs/.vscode/extensions.json
  docs/.vscode/launch.json
  docs/astro.config.mjs
  docs/package.json
  docs/public/logo-dark.svg
  docs/public/logo-light.svg
  docs/src/assets/Mainmatter.astro
  docs/src/assets/logo-dark.svg
  docs/src/assets/logo-light.svg
  docs/src/content/docs/getting-started/installation.md
  docs/src/content/docs/getting-started/installation.mdx
  docs/src/content/docs/getting-started/usage.mdx
  docs/src/content/docs/getting-started/what-is-it.mdx
  docs/src/content/docs/guides/async-transform.mdx
  docs/src/content/docs/guides/task-modifiers.mdx
  docs/src/content/docs/index.mdx
  docs/src/env.d.ts
  docs/src/styles/global.css
  docs/svelte.config.js
  docs/tsconfig.json
  src/lib/tests/expected-transforms/generate-expected.ts
  src/lib/tests/vite.test.ts
  src/lib/vite.ts
Labels: enhancement

#122 Quality-of-life additions
  package.json
Labels: internal

#124 feat: add Mid run cancellation guide
  docs/astro.config.mjs
  docs/src/components/BlankLink.astro
  docs/src/content/docs/explainers/async-transform.mdx
  docs/src/content/docs/explainers/mid-run-cancellation.mdx
  docs/src/content/docs/explainers/task-modifiers.mdx
  docs/src/content/docs/getting-started/installation.mdx
  docs/src/content/docs/getting-started/usage.mdx
  docs/src/content/docs/getting-started/what-is-it.mdx
  docs/src/styles/global.css
Labels: internal

#137 fix: make async transform with dot notation too
  package.json
  src/lib/tests/expected-transforms/dot-notation/code.js
  src/lib/tests/expected-transforms/dot-notation/transform.js
  src/lib/tests/expected-transforms/generate-expected.ts
  src/lib/tests/expected-transforms/with-options/code.js
  src/lib/tests/expected-transforms/with-options/transform.js
  src/lib/tests/task.test.ts
  src/lib/tests/utils.test.ts
  src/lib/vite.ts
  src/vitest-setup.ts
Labels: bug

#132 feat: return derived state to `perform` return value
  src/lib/core.ts
  src/lib/internal/helpers.ts
  src/lib/task.ts
  vite.config.ts
Labels: enhancement
