Repository mainmatter/sheepdog, pull requests merged in 2024-10, with the labels that each got.

#158 docs: add task modifier explainer
  apps/docs/src/content/docs/TimelineExplainer.svelte
  apps/docs/src/content/docs/explainers/task-modifiers.mdx
Labels: documentation

#184 Landing page demo integration
  apps/docs/src/components/Hero.astro
  apps/docs/src/components/Tabs.svelte
  apps/docs/src/components/demo.svelte
  apps/docs/src/components/landing.astro
Labels: documentation

#193 add corepack to fix netlify
  package.json
Labels: internal

#185 fix: way better async transform
  packages/svelte/src/lib/tests/expected-transforms/add-yield-after-await-assignment/code.js
  packages/svelte/src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js
  packages/svelte/src/lib/tests/expected-transforms/statements-in-blocks/transform.js
  packages/svelte/src/lib/vite.ts
Labels: enhancement

#192 fix: properly threeshake the library
  apps/docs/pnpm-lock.yaml
  package.json
  packages/svelte/package.json
  packages/svelte/pnpm-lock.yaml
  packages/svelte/src/lib/task.ts
  packages/svelte/src/lib/tests/threeshake/index.test.ts
  packages/svelte/treeshake.vite.config.ts
  packages/svelte/vite.config.ts
  patches/fixturify-project.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#191 Turn mainmatter footer logo into a link to the svelte consulting page
  apps/docs/src/components/Footer.astro
Labels: documentation

#195 feat: add utils export
  packages/svelte/package.json
Labels: enhancement

#201 Fix dark mode get started button appearing with the wrong colors
  apps/docs/src/components/Hero.astro
Labels: documentation

#203 Add copyright to footer
  apps/docs/src/components/Footer.astro
Labels: documentation

#204 Improve readme
  README.md
Labels: documentation

#202 Add netlify redirects
  apps/docs/astro.config.mjs
  apps/docs/netlify.toml
Labels: internal

#200 Update example code snippets to be closer to actual demo
  apps/docs/src/components/landing.astro
Labels: documentation

#206 Fix logo size issue
  apps/docs/astro.config.mjs
  apps/docs/src/components/Hero.astro
Labels: documentation

#207 Move netlify.toml to root folder
  netlify.toml
Labels: internal

#213 enable gravity again
  .github/workflows/gravity.yml
Labels: internal

#218 Update homepage copy
  apps/docs/src/components/Hero.astro
  apps/docs/src/components/landing.astro
  apps/docs/src/content/docs/index.mdx
Labels: documentation

#221 chore: setup `pkg.pr.new`
  .github/workflows/pkg.pr.new.yml
  packages/svelte/package.json
  packages/svelte/src/lib/tests/threeshake/index.test.ts
  pnpm-lock.yaml
Labels: internal

#223 chore: add plausible analytics
  apps/docs/astro.config.mjs
Labels: documentation, internal
