Repository mainmatter/sheepdog, pull requests merged in 2024-06, with the labels that each got.

#95 Add TaskInstance and derive `last`
  src/lib/index.ts
  src/lib/task.ts
  src/lib/tests/task.test.ts
Labels: enhancement

#98 fix: cancelled instances hanging indefinitely
  src/lib/core.ts
  src/lib/handlers/restart.ts
  src/lib/index.ts
  src/lib/task.ts
  src/lib/tests/components/default.svelte
  src/lib/tests/components/drop.svelte
  src/lib/tests/components/enqueue.svelte
  src/lib/tests/components/keep_latest.svelte
  src/lib/tests/components/link/child.svelte
  src/lib/tests/components/link/parent.svelte
  src/lib/tests/components/restart.svelte
  src/lib/tests/task.test.ts
Labels: bug

#106 chore: delete tgz
  svelte-concurrency-0.0.1.tgz
Labels: internal

#108 Fix docs site title
  docs/src/content/docs/index.mdx
Labels: bug

#112 Add didCancel util
  README.md
  src/lib/index.ts
  src/lib/tests/utils.test.ts
  src/lib/utils.ts
Labels: enhancement

#113 Remove `results` array
  README.md
  src/lib/index.ts
  src/lib/task.ts
Labels: internal
