Repository mainmatter/sheepdog, pull requests merged in 2024-05, with the labels that each got.

#58 feat: better async transform (yield replace await)
  src/lib/task.ts
  src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js
  src/lib/tests/expected-transforms/add-yield-after-await/transform.js
  src/lib/tests/expected-transforms/add-yield-after-multiple-await/transform.js
  src/lib/tests/expected-transforms/task-aliased-plus-task-from-another-library/transform.js
  src/lib/tests/expected-transforms/task-aliased-plus-task-function/transform.js
  src/lib/tests/expected-transforms/task-aliased/transform.js
  src/lib/vite.ts
Labels: enhancement

#62 chore: add svelte exports to avoid warning
  package.json
Labels: internal

#61 feat: link only cancel the instance of the task that was linked
  src/lib/task.ts
  src/lib/tests/components/link/child.svelte
  src/lib/tests/components/link/parent.svelte
  src/lib/tests/task.test.ts
  src/routes/+page.svelte
Labels: bug

#66 feat: more exhaustive async transform
  .gitignore
  package.json
  pnpm-lock.yaml
  src/lib/tests/expected-transforms/add-yield-after-await-assignment/code.js
  src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js
  src/lib/tests/expected-transforms/async-to-generator-no-arrow/code.js
  src/lib/tests/expected-transforms/async-to-generator-no-arrow/transform.js
  src/lib/tests/expected-transforms/statements-in-blocks/code.js
  src/lib/tests/expected-transforms/statements-in-blocks/transform.js
  src/lib/vite.ts
Labels: enhancement

#68 chore: use pnpm 9 in workflows
  .github/workflows/lint.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: internal

#72 chore: upgrade eslint to v9 and flat config
  .eslintignore
  .eslintrc.cjs
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: internal

#67 chore: test for errors thrown in perform
  src/lib/index.ts
  src/lib/tests/components/default.svelte
  src/lib/tests/components/drop.svelte
  src/lib/tests/components/enqueue.svelte
  src/lib/tests/components/link/child.svelte
  src/lib/tests/components/link/parent.svelte
  src/lib/tests/components/restart.svelte
  src/lib/tests/components/wrong-kind.svelte
  src/lib/tests/task.test.ts
  vite.config.ts
Labels: internal

#56 Add keep_latest
  src/lib/handlers/keep_latest.ts
  src/lib/task.ts
  src/lib/tests/components/keep_latest.svelte
  src/lib/tests/task.test.ts
  src/routes/+page.svelte
Labels: enhancement

#88 feat: add performCount to derived state
  src/lib/task.ts
  src/lib/tests/components/default.svelte
  src/lib/tests/components/drop.svelte
  src/lib/tests/components/enqueue.svelte
  src/lib/tests/components/keep_latest.svelte
  src/lib/tests/components/restart.svelte
  src/lib/tests/task.test.ts
Labels: enhancement

#89 feat: abstract task logic to core
  src/lib/core.ts
  src/lib/task.ts
  vite.config.ts
Labels: enhancement

#54 Add docs
  README.md
  src/lib/tests/expected-transforms/generate-expected.ts
  src/lib/tests/vite.test.ts
  src/lib/vite.ts
Labels: documentation
