Repository mainmatter/sheepdog, pull requests merged in 2025-06, with the labels that each got.

#288 docs: docs for multiple packages
  apps/docs/astro.config.mjs
  apps/docs/src/components/Footer.astro
  apps/docs/src/components/Hero.astro
  apps/docs/src/components/SiteTitle.astro
  apps/docs/src/content/docs/index.mdx
  apps/docs/src/content/docs/svelte/explainers/async-transform.mdx
  apps/docs/src/content/docs/svelte/explainers/linking-tasks.mdx
  apps/docs/src/content/docs/svelte/explainers/mid-run-cancellation.mdx
  apps/docs/src/content/docs/svelte/explainers/task-modifiers.mdx
  apps/docs/src/content/docs/svelte/getting-started/installation.mdx
  apps/docs/src/content/docs/svelte/getting-started/usage.mdx
  apps/docs/src/content/docs/svelte/getting-started/what-is-it.mdx
  apps/docs/src/content/docs/svelte/reference/default.mdx
  apps/docs/src/content/docs/svelte/reference/drop.mdx
  apps/docs/src/content/docs/svelte/reference/enqueue.mdx
  apps/docs/src/content/docs/svelte/reference/keep-latest.mdx
  apps/docs/src/content/docs/svelte/reference/restart.mdx
  apps/docs/src/content/docs/svelte/reference/sheepdog-utils.mdx
  apps/docs/src/content/docs/svelte/reference/task-instance.mdx
  apps/docs/src/content/docs/svelte/reference/transform.mdx
  apps/docs/src/content/docs/vanilla/explainers/async-transform.mdx
  apps/docs/src/content/docs/vanilla/explainers/linking-tasks.mdx
  apps/docs/src/content/docs/vanilla/explainers/mid-run-cancellation.mdx
  apps/docs/src/content/docs/vanilla/explainers/task-modifiers.mdx
  apps/docs/src/content/docs/vanilla/getting-started/installation.mdx
  apps/docs/src/content/docs/vanilla/getting-started/usage.mdx
  apps/docs/src/content/docs/vanilla/getting-started/what-is-it.mdx
  apps/docs/src/content/docs/vanilla/reference/default.mdx
  apps/docs/src/content/docs/vanilla/reference/drop.mdx
  apps/docs/src/content/docs/vanilla/reference/enqueue.mdx
  apps/docs/src/content/docs/vanilla/reference/keep-latest.mdx
  apps/docs/src/content/docs/vanilla/reference/restart.mdx
  apps/docs/src/content/docs/vanilla/reference/sheepdog-utils.mdx
  apps/docs/src/content/docs/vanilla/reference/task-instance.mdx
  apps/docs/src/content/docs/vanilla/reference/transform.mdx
  apps/docs/src/env.d.ts
  apps/docs/src/route-data.ts
  apps/docs/src/styles/global.css
  apps/docs/src/utils/is-homepage.ts
  apps/docs/tsconfig.json
Labels: documentation

#319 breaking: bump `@sheepdog/core` version to 1.0
  packages/core/README.md
Labels: breaking

#321 chore: setup release plan to publish to `legacy`
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  packages/core/package.json
  packages/svelte/package.json
  packages/vanilla/package.json
  pnpm-lock.yaml
Labels: internal

#323 fix publishing for legacy version
  .github/workflows/publish.yml
Labels: internal

#328 docs: fix favicon
  README.md
  apps/docs/astro.config.mjs
  apps/docs/public/favicon.svg
  apps/docs/public/logo-dark.svg
  apps/docs/public/logo-light.svg
  apps/docs/src/assets/1c-plus.svg
  apps/docs/src/assets/bg.svg
  apps/docs/src/assets/full-color.svg
  apps/docs/src/assets/logo-dark.svg
  apps/docs/src/assets/logo-light.svg
  apps/docs/src/content/docs/index.mdx
Labels: documentation

#332 chore: add sourcemaps tests
  packages/core/.gitignore
  packages/core/package.json
  packages/core/tests/expected-transforms/add-yield-after-await-assignment/code.js.map
  packages/core/tests/expected-transforms/add-yield-after-await/code.js.map
  packages/core/tests/expected-transforms/add-yield-after-multiple-await/code.js.map
  packages/core/tests/expected-transforms/async-to-generator-no-arrow/code.js.map
  packages/core/tests/expected-transforms/async-to-generator/code.js.map
  packages/core/tests/expected-transforms/dot-notation/code.js.map
  packages/core/tests/expected-transforms/generate-expected.ts
  packages/core/tests/expected-transforms/statements-in-blocks/code.js.map
  packages/core/tests/expected-transforms/task-aliased-plus-task-from-another-library/code.js.map
  packages/core/tests/expected-transforms/task-aliased-plus-task-function/code.js.map
  packages/core/tests/expected-transforms/task-aliased/code.js.map
  packages/core/tests/expected-transforms/with-options/code.js.map
  packages/core/tests/expected-transforms/wrapped-in-transform-import-from-top/code.js.map
  packages/core/tests/expected-transforms/wrapped-in-transform-multiple-imports/code.js.map
  packages/core/tests/expected-transforms/wrapped-in-transform-renamed/code.js.map
  packages/core/tests/expected-transforms/wrapped-in-transform/code.js.map
  packages/core/tests/vite.test.ts
Labels: internal
