Repository mainmatter/sheepdog, pull requests merged in 2025-03, with the labels that each got.

#253 feat: init `@sheepdog/vanilla`
  .github/workflows/pkg.pr.new.yml
  package.json
  packages/core/package.json
  packages/vanilla/.gitignore
  packages/vanilla/package.json
  packages/vanilla/src/index.ts
  packages/vanilla/src/task.ts
  packages/vanilla/src/utils.ts
  packages/vanilla/src/vite.ts
  packages/vanilla/tests/task.test.ts
  packages/vanilla/tests/treeshake/index.test.ts
  packages/vanilla/tests/tsconfig.json
  packages/vanilla/treeshake.vite.config.ts
  packages/vanilla/tsconfig.json
  packages/vanilla/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement

#293 Attempt to fix split renovate config
  renovate.json
Labels: internal

#295 fix: update all the imports
  packages/core/src/index.ts
  packages/core/src/utils.ts
  packages/svelte/src/lib/index.ts
  packages/svelte/src/lib/task.ts
Labels: bug

#297 fix: use spaces in `package.json`'s
  .prettierrc
Labels: internal

#303 chore: add require label workflow
  .github/workflows/require-label.yml
Labels: internal
